config/routes.rb
Rails.application.routes.draw do
  root to: 'users#show'

  resources :services
  resource :session, only: %i[new create destroy]
  resources :users, only: %i[show new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/service.rb
class Service < ApplicationRecord
  validates :id, presence: true, uniqueness: true, numericality: { only_integer: true }
  validates :rank, presence: true, numericality: { only_integer: true }
  validates :title, presence: true, length: { minimum: 4 }
  validates :link, presence: true, uniqueness: true, format: { with: /\Ahttps:\/\/www.codewars.com\/kata\//, message: "only links from Codewards" }
  validates :description, presence: true, length: { minimum: 20 }
  validates :service_class_name, presence: true, uniqueness: true, length: { minimum: 6 },format: { with: /::Base\z/, message: "must end with '::Base'" }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, uniqueness: true
  validates :nickname, presence: true, length: { minimum: 3 }, uniqueness: true
  validate :password_complexity
  validates :password_digest, presence: true

  private
  
  def password_complexity
    return if password.blank? || password =~ /(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])[a-zA-Z0-9;\/\|\\\&\$\#\_\-]{8,20}/

    msg = "complexity requirement not met." \
          "Length should be 8-20 characters and include at least:" \
          "1 uppercase, 1 lowercase, 1 digit and it can include 'special characters like (\/\|\\\&\$\#\_\-)"
    errors.add :password, msg
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  private 

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
  end

  def user_sign_in?
    current_user.present?
  end

  def sign_in(user)
    session[:user_id] = user.id
  end

  def flash_success?(flash)
    flash[:success].present?
  end

  def flash_alert?(flash)
    flash[:alert].present?
  end

  def alerts(flash)
    (flash[:alert].kind_of?(String) ? [flash[:alert]] : flash[:alert])
  end

  def admin_sign_in?
    current_user.present? && current_user[:nickname] == 'admin'
  end

  def require_no_authentication
    return if !user_sign_in?

      flash[:alert] = 'You are already signed in'
      redirect_to root_path
  end

  def require_authentication
    return if user_sign_in?

    flash[:warning] = 'You are not signed in'
    redirect_to root_path
  end

  def tests
    Constant::TESTS
  end

  def exam(number)
    if (tests.keys.min.to_s.to_i < number || tests.keys.min.to_s.to_i == number)
      service_tests_numbers = tests.select{|k, v| k.to_s.to_i <= @completed_solutions.count}
      @service_tests = Service.where(id: (service_tests_numbers.values)).order('id DESC')
    else
      @service_tests = "You don't have enough completed tasks"
    end

    @service_tests
  end
  
  helper_method :user_sign_in?, :flash_success?, :flash_alert?, :alerts, :admin_sign_in, :exam, :tests
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :find_service, only: %i[show update edit destroy]
  helper_method :sort_column, :sort_direction

  def new
    @service = Service.new
  end

  def index
    if current_user.present?
      @completed_solutions = (
        current_user.solutions_numbers.blank? ? 
        "You don't have completed tasks yet" : 
        Service.where(id: JSON.parse(current_user.solutions_numbers)).order('id DESC')
      )

      @service_tests = (
        @completed_solutions.kind_of?(String) ?
        "You don't have enough completed tasks" : exam(@completed_solutions&.count)
      )
    end
    @services = Service.where.not(id: (tests.values)).order(sort_column + " " + sort_direction).page params[:page]
  end

  def show
    @test_input = params[:test_input]
    @result = params[:result]
  end

  def update
    unless params[:service][:test_input].nil?
      @result = @service.service_class_name.constantize.new(params[:service][:test_input]).calculate_result

      Add::Base.new(current_user).add_solution(params[:id]) if current_user.present?

      redirect_to(service_path(id: params[:id], test_input: params[:service][:test_input], result: @result))
    else
      if admin_sign_in?
        if @service.update service_params
          flash.now[:success] = "#{@service.title} kata has been successfully updated!"
          redirect_to service_path(params[:service][:id])
        else
          flash[:alert] = @service.errors.full_messages
          render :edit
        end
      else
        flash[:alert] = "This functionality is available only to the administrator"
        redirect_to services_path
      end
    end
  end

  def edit; end

  def create
    if admin_sign_in?
      @service = Service.create(service_params)
      if @service.valid?
        flash[:success] = "#{@service.title} kata successfully created!"
        redirect_to services_path
      else
        flash[:alert] = @service.errors.full_messages
        redirect_to new_service_path
      end
    else
      flash[:alert] = "This functionality is available only to the administrator"
      redirect_to services_path
    end
  end

  def destroy
    if admin_sign_in?
      @service.destroy
      flash[:alert] = "You removed the #{@service.title} kata"
      redirect_to services_path
    else
      flash[:alert] = "This functionality is available only to the administrator"
      redirect_to services_path
    end
  end

  private

  def find_service
    @service = Service.find(params[:id])
  end

  def sort_column
    Service.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def service_params
    params.require(:service).permit(:id, :rank, :title, :link, :description, :solution_example, :service_class_name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_no_authentication, only: %i[new create]
  before_action :require_authentication, only: :destroy

  def new; end

  def create
    user = User.find_by(email: user_params[:email])
    if user&.authenticate(user_params[:password])
      sign_in user
      flash[:success] = "#{user.name}, you have successfully logged in!"
      
      redirect_to root_path
    else
      flash.now[:alert] = 'Wrong email or password'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:alert] = 'You are logged out'
    redirect_to root_path
  end

  private

  def user_params
    params[:session]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_authentication, only: %i[new create]
  
  def new
    session[:current_time] = Time.now
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.valid?
      sign_in @user
      flash[:success] = "Welcome to the app, #{@user.name}!"
      redirect_to root_path
    else      
      flash[:alert] = @user.errors.full_messages      
      redirect_to new_user_path
    end
  end

  def show
    find_user unless current_user.nil?
    redirect_to services_path
  end

  def destroy
    if admin_sign_in?
      @user_destroy = User.find_by(id: params[:id])
      @user_destroy.destroy
      redirect_to users_path
    else
      flash[:alert] = "This functionality is available only to the administrator"
      redirect_to root_path
    end
  end

  private

  def find_user
    @user = User.find(current_user[:id])
  end

  def user_params
    params.require(:user).permit(:name, :nickname, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => 'header_kata'}
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learning examples RUBY</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <header class="header">
      <div class="header-wrapper">
        <p class="logo"><%= link_to 'Learning examples RUBY', root_path %></a>
        <nav>
          <ul class="ul">
            <% if user_sign_in? %>
              <li><a class="menu"><%= "@#{current_user.nickname}" %></a></li>
              <li><a class="menu"><%= button_to 'Log out', session_path, method: :delete, class: 'button-header' %></a></li>
            <% else %>
              <li><%= link_to 'Join', new_user_path, class: 'button-header menu' %></li>
              <li><%= link_to 'Log in', new_session_path, class: 'menu button-header' %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <section>
      <% if flash_success?(flash) %>
        <p class="mb mt message message-success"><%= flash[:success] %></p>
      <% elsif flash_alert?(flash) %>
        
        <% alerts(flash).each do |msg| %>
          <ol class="mb mt message message-alert">
            <%= "#{msg}!" %><br>
          </ol>
        <% end %>

      <% end %>
    
      <%= yield %>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/services/_completed_solutions.html.erb
<% if @completed_solutions.kind_of?(String) %>
  <%= @completed_solutions %>
<% else %>
  <% @completed_solutions.each do |completed_solution| %>
    <%= link_to("#{completed_solution.id} | #{completed_solution.rank} kyu | #{completed_solution.title}", service_path(completed_solution.id)) %><br>
  <% end %>
<% end %>

app/views/services/_form_service.html.erb
<div class="mg-top sec">
  <%= form_with model: @service do |form| %>

    <div class="mb-3 row h5 max-size ">
      <div class="col-sm-2 col-form-label">
        <%= form.label :id, class: 'required' %>
      </div>

      <div class="col-sm-10-service">
        <%= form.text_field :id, required: true, placeholder: 'Id', class: 'form-control' %>
      </div>
    </div>

    <div class="mb-3 row h5 max-size ">
      <div class="col-sm-2 col-form-label">
        <%= form.label :rank, class: 'required' %>
      </div>

      <div class="col-sm-10-service">
        <%= form.text_field :rank, required: true, placeholder: 'Rank', class: 'form-control' %>
      </div>
    </div>

    <div class="mb-3 row h5 max-size ">
      <div class="col-sm-2 col-form-label">
        <%= form.label :title, class: 'required' %>
      </div>

      <div class="col-sm-10-service">
        <%= form.text_field :title, required: true, placeholder: 'Title', class: 'form-control' %>
      </div>
    </div>

   <div class="mb-3 row h5 max-size ">
      <div class="col-sm-2 col-form-label">
        <%= form.label :link, class: 'required' %>
      </div>

      <div class="col-sm-10-service">
        <%= form.text_field :link, required: true, placeholder: 'Link', class: 'form-control' %>
      </div>
    </div>

    <div class="mb-3 row h5 max-size ">
      <div class="col-sm-3 col-form-label ">
        <%= form.label :description, class: 'required' %>
      </div>

      <div class="col-sm-9-service">
        <%= form.text_area :description, required: true, placeholder: 'Description', class: 'form-control description' %>
      </div>
    </div>

    <div class="mb-3 row h5 max-size ">
      <div class="col-sm-3 col-form-label">
        <%= form.label :solution_example %>
      </div>

      <div class="col-sm-9-service">
        <%= form.text_field :solution_example, placeholder: 'Solution example', class: 'form-control' %>
      </div>
    </div>

    <div class="mb-3 row h5 max-size ">
      <div class="col-sm-3 col-form-label">
        <%= form.label :service_class_name, class: 'required' %>
      </div>

      <div class="col-sm-9-service">
        <%= form.text_field :service_class_name, required: true, placeholder: 'Service class name', class: 'form-control' %>
      </div>
    </div>

    <div class="hr">
      <li><%= form.submit 'Save', class: 'button-header list black' %></li>
      <li><%= link_to 'Back', services_path, class: 'button-header list black' %></li>
    </div>
  <% end %>
</div>

app/views/services/_service_tests.html.erb
<% if @service_tests.kind_of?(String) %>
  <%= @service_tests %>
<% else %>
  <% @service_tests.each do |service_test| %>
    <%= link_to("#{service_test.id} | #{service_test.rank} kyu | #{service_test.title}", service_path(service_test.id)) %><br>
  <% end %>
<% end %>

app/views/services/_services_list.html.erb
<% if current_user.present? && current_user[:nickname] == 'admin' %>
  <%= link_to("Create a new kata", new_service_path, class: 'button-menu red') %>
<% end %>

<b><h4>Sort by: </h4><%= sortable "id" %> | <%= sortable "rank" %> | <%= sortable "title" %></b><hr>

<%= paginate @services %>

<div>
  <ul>
    <% @services.each do |service| %>
      <li class="list"><%= link_to("#{service.id} | #{service.rank} kyu | #{service.title}", service_path(service.id), :class => "kata") %>      
        <% if current_user.present? && current_user[:nickname] == 'admin' %>
          | <%= link_to image_tag("https://i.ibb.co/sPS7p6x/pencil.png", class: 'font'), edit_service_path(service), title: "Edit service" %>
          | <%= link_to image_tag("https://i.ibb.co/gVPs43F/trash.png", class: 'font1'), service_path(service), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        <% end %>
      </li><br>
    <% end %>
  </ul>
</div>

<%= paginate @services %>

app/views/services/edit.html.erb
<section>
  <div>
    <h2 class="title">Edit service</h2>
    
    <%= render 'form_service', service: @service %>
  </div>
</section>  

app/views/services/index.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="kata-tab" data-bs-toggle="tab" data-bs-target="#kata-tab-pane" type="button" role="tab" aria-controls="kata-tab-pane" aria-selected="true">
      Kata
    </button>
  </li>

  <% if current_user.present? %>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="completed_solutions-tab" data-bs-toggle="tab" data-bs-target="#completed_solutions-tab-pane" type="button" role="tab" aria-controls="completed_solutions-tab-pane" aria-selected="false">
        Solutions
      </button>
    </li>

    <li class="nav-item" role="presentation">
      <button class="nav-link" id="service_tests-tab" data-bs-toggle="tab" data-bs-target="#service_tests-tab-pane" type="button" role="tab" aria-controls="service_tests-tab-pane" aria-selected="false">
        Tests
      </button>
    </li>

    <% if current_user[:nickname] == 'admin' %>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="users-tab" data-bs-toggle="tab" data-bs-target="#users-tab-pane" type="button" role="tab" aria-controls="users-tab-pane" aria-selected="false">
          Users
        </button>
      </li>
    <% end %>
  <% end %>
</ul>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="kata-tab-pane" role="tabpanel" aria-labelledby="kata-tab" tabindex="0">
    <%= render 'services_list' %>
  </div>

  <% if current_user.present? %>
    <div class="tab-pane fade" id="completed_solutions-tab-pane" role="tabpanel" aria-labelledby="completed_solutions-tab" tabindex="0">
      <%= render 'completed_solutions' %>
    </div>

    <div class="tab-pane fade" id="service_tests-tab-pane" role="tabpanel" aria-labelledby="service_tests-tab" tabindex="0">
      <%= render 'service_tests' %>
    </div>

    <% if current_user[:nickname] == 'admin' %>
      <div class="tab-pane fade" id="users-tab-pane" role="tabpanel" aria-labelledby="users-tab" tabindex="0">
      
        <% UsersList::Base.new(current_user).show_all_users.each do |user| %>
          <li class="list">
            <%= "#{user.id} | #{user.name} | #{user.nickname} | #{user.email} | #{user.solutions_numbers} | " %>
            <%= link_to image_tag("https://i.ibb.co/gVPs43F/trash.png", class: 'font1'), user_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </li><br>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/services/new.html.erb
<section>
  <div>
    <h2 class="title">New service</h2>

    <%= render 'form_service' %>
  </div>
</section>

app/views/services/show.html.erb
<section>
  <h2 class="title"><%= @service.title %></h1>
  <% unless tests.values.include?(@service.id) %>
    <%= link_to("Codewars Link", @service.link, class: "kata link") %>
  <% end %>

  <h3>Description:</h3>
  <%= @service.description.html_safe %><hr>
  
  <% unless tests.values.include?(@service.id) %>
    <h3>Solution example:</h3>
    <div class="box">
      <%= @service.solution_example.html_safe %>
    </div>
  <% end %>

  <hr>
  <%= form_with model: @service, method: :patch, url: service_path(@service.id) do |form| %>
    <% unless tests.values.include?(@service.id) %>
      <%= form.label :test_input, class: "form sm" %><br>
      <%= form.text_field :test_input, value: @test_input %>
    <% else %>

      <div class="mb-3 row h5 max-size ">
        <div class="col-sm-3 col-form-label ">
          <%= form.label 'Your solution:' %>
        </div>

        <div class="col-sm-9-service">
          <%= @service.solution_example.split(",  ")[0].html_safe %><br>
          <%= form.text_area :test_input, placeholder: 'Your solution:', value: @test_input, class: 'form-control resalt_240' %>
          end
        </div>
      </div>
    <% end %>  
    <div class="hr">
      <%= form.submit "Get result", class: 'button main' %>
    </div>
  <% end %>

  <% unless tests.values.include?(@service.id) %>
    <h3>Result:</h3>
    <textarea><%= @result %></textarea><br>
  <% else %>
    <div class="mb-3 row h5 max-size ">
      <div class="col-sm-3 col-form-label ">
        <h3>Result:</h3>
      </div>

      <div class="col-sm-9-service">
        <textarea class="form-control resalt_60"><%= @result %></textarea><br>
        <%= ('Your decision is '+(@result == (@service.solution_example.split(",  ")[1]) ? 'correct' : 'wrong')) unless @result.blank? %>
      </div>
    </div>
  <% end %>

  <div class="hr">
    <li><%= link_to 'Back', services_path, class: 'button-header black' %></li>
    <% if current_user.present? && current_user[:nickname] == 'admin' %>
      <li><%= link_to 'Edit service', edit_service_path(@service), class: 'button-header red' %></li>
      <li><%= button_to 'Delete service', service_path(@service), method: :delete, class: 'button-header red' %></li>
    <% end %>
  </div>
</section>

app/views/users/new.html.erb
<div class="small">
  <div class="conteiner">  
    <h2 class="title">Join the community!</h2>
    
    <div class="mg-top">      
      <%= form_with model: @user do |form| %>

        <div class="mb-3 row h5">
          <div class="col-sm-2 col-form-label">
            <%= form.label :name, class: 'required' %>
          </div>

          <div class="col-sm-9">
            <%= form.text_field :name, placeholder: 'Your name', class: 'form-control' %>
          </div>
        </div>

        <div class="mb-3 row h5">
          <div class="col-sm-2 col-form-label">
            <%= form.label :nickname, class: 'required' %>
          </div>

          <div class="col-sm-9">
            <%= form.text_field :nickname, placeholder: 'Your nickname', class: 'form-control' %>
          </div>
        </div>

        <div class="mb-3 row h5">
          <div class="col-sm-2 col-form-label">
            <%= form.label :email, class: 'required' %>
          </div>

          <div class="col-sm-9">
            <%= form.email_field :email, placeholder: 'Email', class: 'form-control' %>
          </div>
        </div>

        <div class="mb-3 row h5">
          <div class="col-sm-2 col-form-label">
            <%= form.label :password, class: 'required' %>
          </div>

          <div class="col-sm-9">
            <%= form.password_field :password, placeholder: 'Password', class: 'form-control' %>
          </div>
        </div>

        <div class="mb-3 row h5">
          <div class="col-sm-2 col-form-label">
            <%= form.label :password_confirmation, 'Confirm', class: 'required' %>
          </div>

          <div class="col-sm-9">
            <%= form.password_field :password_confirmation, placeholder: 'Password confirmation', class: 'form-control' %>
          </div>
        </div>

        <div class="hr">
          <li><%= form.submit 'Sign in', class: 'button-header list black' %></li>
          <li><%= link_to 'Back', services_path, class: 'button-header list black' %></li>
        </div>      
      <% end %>
    </div>
  </div>
</div>